### ISSUE TITLE
Simulations Seems to be hanging & not running in parallel

### ISSUE THREAD

**Issue by Walshest** [tlkenergy/sim-tlk#30] opened 2022-12-15 17:41 UTC
Hi, 
I have been running some simulations and I have two issues: 
1. Simulation seems to be hanging and taking over 40 minutes to complete [10 hrs, 10 s timestep]
2. Simulations are not running in parallel. (only 1 at a time) 
<img width="424" alt="image" src="https://user-images.githubusercontent.com/45364510/207930266-ee1efce8-a69f-49cf-be04-4b29e182fa1a.png">

**Comment by PascalPadberg** [comment] 2022-12-19 09:21
Thanks for reporting it, we are looking into it

**Comment by magraeber** [comment] 2022-12-20 10:18
The second issue was caused by an outdated image at AWS for worker instances. It's fixed now.

**Closed as completed** 2022-12-20 10:22 UTC
