### ISSUE TITLE
Not able to change the unit of an output in the plot

### ISSUE THREAD

**Issue by Walshest** [tlkenergy/sim-tlk#26] opened 2022-09-08 10:21 UTC
For the output COP there is no unit with this. 
Therefore it isn't read by Sim.TLK; however I cannot select a unit then or save the plot. 
<img width="276" alt="image" src="https://user-images.githubusercontent.com/45364510/189098254-e385cfab-f0a0-4330-b5f9-08d5d53e7163.png">

**Comment by PascalPadberg** [comment] 2022-09-08 11:45
We are going to add all units to the selection, however, if no units is defined in the model, no unit conversion is possible and the unit selected here must be same as intended in the model. We cannot check it, though.

**Comment by PascalPadberg** [comment] 2022-09-08 13:33
Resolved with v2.1.0

**Closed as completed by PascalPadberg** 2022-09-08 13:33 UTC
