### ISSUE TITLE
Improvements of pH diagram

### ISSUE THREAD

**Issue by Walshest** [tlkenergy/sim-tlk#7] opened 2021-10-22 10:08 UTC
@pascal mentioned that the pH diagram interface will be improved. 

This will be that it will identify the system states and cycles in a more automated way, similar to DaVE tool. 

Can you close this when it is finished please, so we know it is implemented?

**Comment by Walshest** [comment] 2022-09-02 07:43
Hi @PascalPadberg , 
What is the status of the pH diagrams? 
I can see there is some implementation, but it doesn't work. 
1. Cannot save the pH diagram plot: 
<img width="598" alt="image" src="https://user-images.githubusercontent.com/45364510/188085009-6445589d-1fb6-4c7d-bef3-9cf946e598dc.png">
2. Fluid just shows numbers and I believe that should be linked with ENUMs. 
<img width="564" alt="image" src="https://user-images.githubusercontent.com/45364510/188085117-b07ce44f-34a2-4a9e-bf83-a13325ef0eb8.png">

Should the feature be working now?

**Comment by PascalPadberg** [comment] 2022-09-02 07:45
It's not working right now, but it will be next week, because we are rolling out an update today and beginning of next week with multiple new features

**Comment by Walshest** [comment] 2022-09-02 07:58
> It's not working right now, but it will be next week, because we are rolling out an update today and beginning of next week with multiple new features

Great, looking forward to it. 
It would be great if you can provide a list of the features that will be implemented. :)

**Comment by PascalPadberg** [comment] 2022-09-05 08:22
resolved with v2.0.0

**Closed as completed by PascalPadberg** 2022-09-05 08:22 UTC
Labels: enhancement

**Comment by Walshest** [comment] 2022-09-08 09:32
> resolved with v2.0.0

Hi @PascalPadberg , 
I have tested out the pH plots with a simple model and it doesn't work. 
I am not able to save the pH diagram (no warnings/ errors are given back)

The code for the pH diagrams seems to give an extra statepoint back and this could be the issue?: 
_statePoint_ is there twice
`{
  "name": "state-points",
  "xyVariableGroupName": "VLE Fluid ID 2",
  "variables": [
    {
      "name": "statePoint",
      "xVariable": {
        "value": "statePoint:h"
      },
      "yVariable": {
        "value": "statePoint:p"
      }
    },
    {
      "name": "statePoint4",
      "xVariable": {
        "value": "statePoint4:h"
      },
      "yVariable": {
        "value": "statePoint4:p"
      }
    },
    {
      "name": "statePoint5",
      "xVariable": {
        "value": "statePoint5:h"
      },
      "yVariable": {
        "value": "statePoint5:p"
      }
    },
    {
      "name": "statePoint1",
      "xVariable": {
        "value": "statePoint1:h"
      },
      "yVariable": {
        "value": "statePoint1:p"
      }
    },
    {
      "name": "statePoint3",
      "xVariable": {
        "value": "statePoint3:h"
      },
      "yVariable": {
        "value": "statePoint3:p"
      }
    },
    {
      "name": "statePoint",
      "xVariable": {
        "value": "statePoint:h"
      },
      "yVariable": {
        "value": "statePoint:p"
      }
    }
  ]
}`

**Comment by PascalPadberg** [comment] 2022-09-08 09:37
Hi Stefan,
it was another issue. But we just fixed it. Should be online in 5 minutes.
Then I will test it as well.

**Comment by Walshest** [comment] 2022-09-08 09:38
Additionally there is a limitation that the Fluid is not read from the simulation model when it is being simulated. 
- This leads to a potential issue that the incorrect refrigerant dome is plotted
- We have the option with some models that we are able to define through an ENUM which Refrigerant we are using. This is not possible to change the .FMU now

![image](https://user-images.githubusercontent.com/45364510/189089092-ed7c0d26-bd36-4c81-9aad-f444476882d2.png)

**Comment by Walshest** [comment] 2022-09-08 09:39
There is also a new saving issue which could be causing the saving problem: 
<img width="208" alt="image" src="https://user-images.githubusercontent.com/45364510/189089629-7f0e948f-3acb-454a-9a00-f525172d6174.png">
Sometimes the .FMU is exported without this output/ variable of CPUTime

**Comment by PascalPadberg** [comment] 2022-09-08 09:41
Yes, that limitation is due to the fact, that the refrigerant cannot be read from the FMU. 

We are going to add the option, that the refrigerant selection can be connected to a parameter. It is already possible, just not in the fmu config interface. So if you need it, I could configure it for you. The problem is, that you need to know the IDs of the fluid in our data base, because strings do not work with FMUs.

**Comment by PascalPadberg** [comment] 2022-09-08 11:00
I thought about it during lunch break and I think it is indeed possible to get around the problem with fluid IDs. But I'll have to test it and and it would take some time to implement
